//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kts.RefactorThis.DataAccess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SQLStatements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLStatements() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kts.RefactorThis.DataAccess.SQLStatements", typeof(SQLStatements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Product (Id, Name, Description, Price, DeliveryPrice)
        /// OUTPUT INSERTED.Id
        /// VALUES (NEWID(), @Name, @Description, @Price, @DeliveryPrice).
        /// </summary>
        public static string CreateProduct {
            get {
                return ResourceManager.GetString("CreateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO ProductOption(Id, ProductId, Name, Description)
        /// OUTPUT INSERTED.Id
        /// VALUES (NEWID(), @ProductId, @Name, @Description).
        /// </summary>
        public static string CreateProductOption {
            get {
                return ResourceManager.GetString("CreateProductOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM ProductOption WHERE ProductId = @Id;
        ///DELETE FROM Product WHERE Id = @Id;.
        /// </summary>
        public static string DeleteProductById {
            get {
                return ResourceManager.GetString("DeleteProductById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM ProductOption WHERE Id = @OptionId AND ProductId = @ProductId.
        /// </summary>
        public static string DeleteProductOptionByIdAndProductId {
            get {
                return ResourceManager.GetString("DeleteProductOptionByIdAndProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM ProductOption WHERE ProductId = @ProductId.
        /// </summary>
        public static string DeleteProductOptionByProductId {
            get {
                return ResourceManager.GetString("DeleteProductOptionByProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id, Name, Description, Price, DeliveryPrice
        /// FROM Product 
        /// ORDER BY Id
        /// OFFSET @Offset ROWS FETCH NEXT @Limit ROWS ONLY.
        /// </summary>
        public static string GetAllProducts {
            get {
                return ResourceManager.GetString("GetAllProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id, Name, Description, Price, DeliveryPrice
        /// FROM Product
        /// WHERE Id = @Id.
        /// </summary>
        public static string GetProductById {
            get {
                return ResourceManager.GetString("GetProductById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id, Name, Description
        /// FROM ProductOption
        /// WHERE  Id = @OptionId AND ProductId = @ProductId.
        /// </summary>
        public static string GetProductOptionByIdAndProductId {
            get {
                return ResourceManager.GetString("GetProductOptionByIdAndProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id, Name, Description
        /// FROM ProductOption
        /// WHERE ProductId = @ProductId
        /// ORDER BY Id
        /// OFFSET @Offset ROWS FETCH NEXT @Limit ROWS ONLY.
        /// </summary>
        public static string GetProductOptionByProductId {
            get {
                return ResourceManager.GetString("GetProductOptionByProductId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT Id, Name, Description, Price, DeliveryPrice
        /// FROM Product 
        /// WHERE Name = @Name
        /// ORDER BY Id
        /// OFFSET @Offset ROWS FETCH NEXT @Limit ROWS ONLY.
        /// </summary>
        public static string GetProductsByName {
            get {
                return ResourceManager.GetString("GetProductsByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Product SET Name = @Name, Description = @Description,
        /// Price = @Price, DeliveryPrice = @DeliveryPrice
        /// WHERE Id = @Id.
        /// </summary>
        public static string UpdateProductById {
            get {
                return ResourceManager.GetString("UpdateProductById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE ProductOption SET Name = @Name, Description = @Description
        /// WHERE Id = @OptionId AND ProductId = @ProductId.
        /// </summary>
        public static string UpdateProductOptionById {
            get {
                return ResourceManager.GetString("UpdateProductOptionById", resourceCulture);
            }
        }
    }
}
